name: "ruby cache key CI workflow OS matrix"

on:
  push:
    branches: [ dev ]

jobs:
  
  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-osmatrix-cache:
    name: "OS matrix testing, include the matrix variables in cache key"
    runs-on: ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v2 #include the matrix variables in your cache key
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-        
    - run: bundle install
    - run: bundle exec rake      

