

name: "ruby CI workflow ubuntu"


on:
  push:
    branches: [ dev ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test:
    name: "Specifying the Ruby version"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6  # Not needed with a .ruby-version file
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake

  
  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test-26:
    name: "Specifying the Ruby version 2.6"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6  # Not needed with a .ruby-version file
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake      

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-multiple-versions:
    name: "Testing with multiple versions of Ruby on ubuntu-18.04"
    runs-on: ubuntu-latest #ubuntu-18.04
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake   

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-multiple-versions-ubuntu-2004-job:
    name: "Testing with multiple versions of Ruby on ubuntu-20.04"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake 

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-multiple-versions-ubuntu-1604-job:
    name: "Testing with multiple versions of Ruby on ubuntu-16.04"
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby-version: [2.7.x, 2.6.x, 2.5.x]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: "Install dependencies"
      run: bundle install
    - name: "Run tests"
      run: bundle exec rake  

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-test-caching:
    name: "Specifying the Ruby version 2.6"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up Ruby"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6  #Not needed with a .ruby-version file
        bundler-cache: true #Caching dependencies
    - name: "Install dependencies"
      run: bundle install #Installing dependencies with Bundler
    - name: "Run tests"
      run: bundle exec rake       

  # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-ruby
  ruby-caching:
    name: "Caching without setup-ruby"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3     

